name: fonbnktest
publish_to: none

environment:
  sdk: ^3.9.2

workspace:
  - packages/authentication_repository
  - packages/api_client
  - packages/app

dependencies:
  equatable: ^2.0.7
  logger: ^2.6.2

dev_dependencies:
  test: ^1.25.15
